add a few common sites to default no skip list
sblask/webextension-skip-redirect pull request #337
Opened 2023-01-23 17:54 UTC by wesinator

add a few common bad redirects to the default no skip list

close #312 , #103

2023-03-13 13:39 UTC, RiZKiT commented
I would suggest to simplify the rules to the format of `//subdomain.domain.tld/`, no need for http/https or the trailing wildcard. Additionally sorting them alphabetically to prevent accidental duplicates when extending later.

2023-04-17 02:22 UTC, pe1uca requested changes

2023-04-17 02:22 UTC, pe1uca commented on background.js
> +    "//www.linkedin.com/cws/",
Personally I wouldn't like to have by default skips for facebook, google, twitter or outlook, IMO the extension should block all redirects by default.    

If you'd like to provide this list of "include these if you are having issues on these sites" it should be optional, maybe in a FAQ section for people to copy and paste or a separate list to toggle.

2023-11-20 23:52 UTC, sblask commented
I won't maintain a list of specific websites, so this is a non starter.

2023-11-20 23:52 UTC, closed without merging